### ISSUE TITLE
URGENT : L'adresse de l'url de l'api d'authentification est en dur dans le js-sdk, il faut qu'elle soit en paramétre

### ISSUE THREAD

**Issue by fsebbah** [ma-residence/js-sdk#10]
L'adresse URL n'est plus en http mais https, 
il faut le changer dans le js-sdk pour qu'il prenne le paramètre envoyé et non la constante.

**Comment by maxperrimond** [comment]
Elle n'est pas "en dur" mais ajouter par défaut si elle n'est pas spécifié. Elle peut être défini dans le constructeur
