### ISSUE TITLE
Obtenir un code retour en cas d'échec d'authentification

### ISSUE THREAD

**Issue by fsebbah** [ma-residence/js-sdk#5]
Le retour d'un échec d'authentification renvoie le message:
error Error: Authentication error!
    at http://ma-residence.goodiy.io/bower_components/js-sdk/mr-client.min.js:1:3928

Et une erreur JS:
mr-client.min.js:1 GET http://api.ma-residence.fr/oauth/v2/token?client_id=c4ee8504-80d2-11e6-8f1f…socwos08k&username=user.a@ma-residence.fr&password=dsq&grant_type=password 400 (Bad Request)

Il serait mieux d'avoir un code de type 206 en cas de succès et 400 cas d'échec.

**Comment by maxperrimond** [comment]
C'est le comportement voulu mais l'erreur provenant de l'API peut remplacer le message dans l'exception

**Comment by maxperrimond** [comment]
Pour des raisons de concept avec le front, il faut ajouter un listener dans le client en cas d'echec d'authentification
