### ISSUE TITLE
Retour: SyntaxError: Unexpected end of input du SDK sur un PUT

### ISSUE THREAD

**Issue by fsebbah** [ma-residence/js-sdk#6]
Dans le cas d'un PUT des roles pour un user via la route 
http://api.ma-residence.fr/back-office/users/3e74daa6-c07d-11e6-89ad-170c89c7720f/roles
, l'update se déroule bien: code http 200 et 202.
Le SDK renvoie un message d'erreur: SyntaxError: Unexpected end of input

**Comment by maxperrimond** [comment]
L'erreur provient en voulant parser un json d'une response vide
